name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test ${{ matrix.platform }}
    runs-on: macos-15
    strategy:
      matrix:
        platform: [iOS, macOS]
        include:
          - platform: iOS
            destination: "platform=iOS Simulator,name=iPhone 16 Pro,OS=latest"
          - platform: macOS
            destination: "platform=macOS"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Xcode
        uses: actions/cache@v4
        with:
          path: |
            ~/Library/Developer/Xcode/DerivedData
            ~/Library/Caches/org.swift.swiftpm
          key: ${{ runner.os }}-${{ matrix.platform }}-xcode-${{ hashFiles('Package.swift', 'Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.platform }}-xcode-

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Install brew
        run: brew bundle

      - name: Verify Macros
        run: defaults write com.apple.dt.Xcode IDESkipMacroFingerprintValidation -bool YES

      - name: Build and Test
        run: |
          set -o pipefail && xcodebuild test \
          -scheme BrzzUtils-Package \
          -destination '${{ matrix.destination }}' \
          -derivedDataPath ~/Library/Developer/Xcode/DerivedData \
          -resultBundlePath TestResults-${{ matrix.platform }} \
          | xcbeautify
